language: ruby
cache: bundler

rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - rogelio.sevilla1@gmail.com
    on_failure: change
    on_success: never